spring:
  datasource:
    url:jdbc:h2:mem: devdb
    driverClassName: org.h2.Driver
    username: dev
    password: dev
    data: classpath:data-user.sql, classpath:data-account.sql, classpath:data-transaction.sql
