spring:
  h2:console:enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url:jdbc:h2:mem: testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    data: classpath:data-user.sql, classpath:data-account.sql, classpath:data-transaction.sql
  batch:
    initialize-schema: always
